=== renatof/FaaSr/schema/FaaSr.schema.json
{
  "$comment":"work in progress - we want a JSON schema to validate a payload, there is an R library for this - https://cran.r-project.org/web/packages/jsonvalidate/vignettes/jsonvalidate.html",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://flare-forecast.org/FaaSr.schema.json",
  "title": "FaaSr invocation payload",
  "description": "Schema for an invocation of FaaSr",
  "type": "object",
  "properties": {
    "FunctionInvoke": {
      "description": "The name of the R function to be invoked by this action",
      "type": "string",
      "minLength": 1
    },
    "InvocationID": {
      "description": "The unique ID used throughout all action invocations for this workflow",
      "type": "string"
    },
    "LoggingServer": {
      "description": "The name of the logging server to use - must match an S3 server defined under DataStores",
      "type": "string",
      "minLength": 1
    },
    "FunctionList": {
      "description": "A list of one or more functions that describes the workflow",
      "type": "object",
      "minProperties": 1,
      "propertyNames":{"minLength": 1},
      "minProperties": 1,
      "patternProperties": {
        "":{
            "type":"object",
            "properties":{
                  "FaaSServer":{"type":"string","minLength": 1},
                  "Actionname":{"type":"string","minLength": 1},
                  "Arguments":{"type":"object"},
                  "InvokeNext":{"type":["string", "array"]}
                  },
            "required":["FaaSServer", "Actionname"],
            "additionalProperties": false
        }
      }
    },
    "ComputeServers": {
      "description": "A list of one or more FaaS compute servers used in the workflow",
      "type": "object",
      "minProperties": 1,
      "propertyNames":{"minLength": 1},
      "patternProperties": {
        "":{
            "type":"object",
            "oneOf":[
            {
            "properties":{
                  "FaaSType":{"enum":["OpenWhisk"]},
                  "Region":{"type":"string","minLength": 1},
                  "Endpoint":{"type":"string","minLength": 1},
                  "Namespace":{"type":"string","minLength": 1},
                  "API.key":{"type":"string","minLength": 1}
                  },
            "required":["FaaSType", "Region", "Endpoint", "Namespace", "API.key"],
            "additionalProperties": false
            },
            {
            "properties":{
                  "FaaSType":{"enum":["Lambda"]},
                  "Region":{"type":"string","minLength": 1},
                  "AccessKey":{"type":"string","minLength": 1},
                  "SecretKey":{"type":"string","minLength": 1}
                  },
            "required":["FaaSType", "Region", "AccessKey", "SecretKey"],
            "additionalProperties": false
            }
            ]
          }
        }
    },
    "DataStores": {
      "description": "A list of one or more S3 data servers used in the workflow",
      "type": "object",
      "minProperties": 1,
      "propertyNames":{"minLength": 1},
      "patternProperties": {
        "":{
            "type":"object",
            "properties":{
                  "Endpoint":{"type":"string","minLength": 1},
                  "Protocol":{"type":"string","minLength": 1},
                  "AccessKey":{"type":"string","minLength": 1},
                  "SecretKey":{"type":"string","minLength": 1},
                  "Bucket":{"type":"string","minLength": 1},
                  "Region":{"type":"string","minLength": 1},
                  "Writable":{"type":"string","minLength": 1}
                  },
            "required":["Endpoint", "Protocol", "AccessKey", "SecretKey", "Bucket", "Region"],
            "additionalProperties": false
        }
      }
    },
   "ActionContainers": {
      "description": "A mapping of action names to containers(Docker Hub)",
      "type": "object",
      "minProperties": 1,
      "propertyNames":{"minLength": 1},
      "patternProperties": {
        "":{"type":"string","minLength": 1}
      }
    },
   "UserRcodeURL": {
      "description": "User R code from github URL",
      "type": "object",
      "minProperties": 1,
      "propertyNames":{"minLength": 1},
      "patternProperties":{
        "":{
          "oneOf":[
            {"type":"string","minLength": 1},
            {"type":"array","minItems":1}
            ]
        }
      }
    }     
  },
  "required": [ "FunctionInvoke", "LoggingServer", "FunctionList", "ComputeServers", "DataStores", "ActionContainers" ]
}

=== renatof/FaaSr/examples/simple_sequence.json
{
"FunctionInvoke": "F1",
"InvocationID": "0b7f133e-bdfc-4d69-842f-63b15d9e68a8",
"LoggingServer":"S3_A",
"FunctionList":{
        "F1":{
                "FaaSServer":"ow_A",
                "Actionname":"f1",
                "Arguments":{
                        "input1":"input1.csv",
                        "input2":"input2.csv",
                        "output":"output1.csv"
                },
                "InvokeNext":["F2"]
        },
        "F2":{
                "FaaSServer":"ow_A",
                "Actionname":"f2",
                "Arguments":{
                        "input":"output1.csv",
                        "output":"output2.csv"
                }
        }
},
"ComputeServers":{
        "ow_A":{
                "FaaSType": "OpenWhisk",
                "Region":"us-south",
                "Endpoint":"https://api.us-south.cf.cloud.ibm.com",
                "Namespace":"000000000000000000000000",
                "API.key":"000000000000000000000000"
        },

        "lambda_a":{
                "FaaSType": "Lambda",
                "Region":"us-east",
                "AccessKey":"https://api.us-south.cf.cloud.aws.com",
                "SecretKey":"000000000000000000000000"
        }

},
"DataStores":{
        "S3_A":{
                "Endpoint":"my_s3",
                "Protocol":"https",
                "AccessKey":"000000000000000000000000",
                "SecretKey":"000000000000000000000000",
                "Bucket":"spark7-bucket-01",
                "Region":"us-east-1",
                "Writable":"TRUE"
        }
},
"ActionContainers":{
        "f1":"dockerhub_containerX",
        "f2":"dockerhub_containerY",
        "f3":"dockerhub_containerX"
        }
}

=== renatof/FaaSr/examples/example_payload_for_gh_actions.json
{
"FunctionInvoke": "F1",
"InvocationID": "000",
"LoggingServer":"S3_A",
"FunctionList":{
        "F1":{
                "FaaSServer":"github_a",
                "Actionname":"faasr",
                "Arguments":{
                        "input1":"input1.csv",
                        "input2":"input2.csv",
                        "output":"output1.csv"
                },
                "InvokeNext":["F3","F2"]
        },
        "F2":{
                "FaaSServer":"github_a",
                "Actionname":"faasr",
                "Arguments":{
                        "input1":"input1.csv",
                        "input2":"output1.csv",
                        "output":"output2.csv"
                },
                "InvokeNext":["F4"]
        },
        "F3":{
                "FaaSServer":"github_a",
                "Actionname":"faasr",
                "Arguments":{
                        "input1":"input2.csv",
                        "input2":"output1.csv",
                        "output":"output3.csv"
                },
                "InvokeNext":["F4"]
        },
        "F4":{
                "FaaSServer":"github_a",
                "Actionname":"faasr",
                "Arguments":{
                        "input1":"output2.csv",
                        "input2":"output3.csv",
                        "output":"output4.csv"
                }
        }
},
"ComputeServers":{
        "github_a":{
                "FaaSType": "GitHubActions",
                "UserName":"yourGithubAccountName",
                "RepoName":"serverless_github_action4",
                "WorkflowName":"main-workflow.yml",
                "Token":"GITHUB_gita_TOKEN",
                "Ref":"main"
        },
        "lambda_a":{
                "FaaSType": "Lambda",
                "Region":"us-east-2",
                "AccessKey":"GITHUB_lambda_ACCESS_KEY",
                "SecretKey":"GITHUB_lambda_SECRET_KEY"
        }
},
"DataStores":{
        "S3_A":{
                "Endpoint":"my_s3",
                "Protocol":"https",
                "AccessKey":"GITHUB_S3_ACCESS_KEY",
                "SecretKey":"GITHUB_S3_SECRET_KEY",
                "Bucket":"4662-east1",
                "Region":"us-east-1",
                "Writable":"TRUE"
        },
        "S3_B":{
            "Endpoint":"my_s3",
            "Protocol":"https",
            "AccessKey":"GITHUB_S3_ACCESS_KEY",
            "SecretKey":"GITHUB_S3_SECRET_KEY",
            "Bucket":"4662-east1",
            "Region":"us-east-1",
            "Writable":"TRUE"
        }
},
"ActionContainers":{
        "f1":"dockerhub_containerX",
        "f2":"dockerhub_containerY",
        "f3":"dockerhub_containerX"
        }
}
